version: "3.9"

services:
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - ./auth-service/.env.prod
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "--timeout=5", "http://localhost:4000/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3

  billing-service:
    build:
      context: ./billing-service
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    env_file:
      - ./billing-service/.env.prod
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "--timeout=5", "http://localhost:4001/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3

  management-service:
    build:
      context: ./management-service
      dockerfile: Dockerfile
    ports:
      - "4002:4002"
    env_file:
      - ./management-service/.env.prod
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "--timeout=5", "http://localhost:4002/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./gateway/.env.prod
    environment:
      - NODE_ENV=production
      - AUTH_SERVICE_URL=http://auth-service:4000
      - BILLING_SERVICE_URL=http://billing-service:4001
      - MANAGEMENT_SERVICE_URL=http://management-service:4002
    depends_on:
      auth-service:
        condition: service_healthy
      billing-service:
        condition: service_healthy
      management-service:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "--timeout=5", "http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3