version: "3.9"

services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile.dev
    container_name: gateway
    ports:
      - "8000:8000"      
    env_file:
      - ./gateway/.env.dev
    environment:
      AUTH_SERVICE_URL: http://auth-service:4000
      BILLING_SERVICE_URL: http://billing-service:4001
      MANAGEMENT_SERVICE_URL: http://management-service:4002
      NODE_ENV: development
    volumes:
      - ./gateway:/usr/src/app
      - gateway_node_modules:/usr/src/app/node_modules
    command: npm run dev
    depends_on:
      - auth-service
      - billing-service
      - management-service

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile.dev
    container_name: auth-service
    ports:
      - "4000:4000"
    env_file:
      - ./auth-service/.env.dev
    environment:
      NODE_ENV: development
    volumes:
      - ./auth-service:/usr/src/app
      - auth_node_modules:/usr/src/app/node_modules
    command: npm run dev

  billing-service:
    build:
      context: ./billing-service
      dockerfile: Dockerfile.dev
    container_name: billing-service
    ports:
      - "4001:4001"
    env_file:
      - ./billing-service/.env.dev
    environment:
      NODE_ENV: development
    volumes:
      - ./billing-service:/usr/src/app
      - billing_node_modules:/usr/src/app/node_modules
    command: npm run dev

  management-service:
    build:
      context: ./management-service
      dockerfile: Dockerfile.dev
    container_name: management-service
    ports:
      - "4002:4002"
    env_file:
      - ./management-service/.env.dev
    environment:
      NODE_ENV: development
    volumes:
      - ./management-service:/usr/src/app
      - management_node_modules:/usr/src/app/node_modules
    command: npm run dev

volumes:
  gateway_node_modules:
  auth_node_modules:
  billing_node_modules:
  management_node_modules: