FROM node:22-alpine

RUN apk add --no-cache git

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install -g nodemon ts-node typescript && \
    npm install

COPY . .

EXPOSE 4000

CMD ["npm", "run", "dev"]